"""Candidate direction-split models for the step 2 tournament.

The plan's rule is that LightGBM is not automatically the product winner:
four candidates get identical folds, and the simplest statistically defensible
one is selected by a pre-registered deterministic rule. That framing matters
here because the tracked `data/dirsplit/train_report.json` already shows the
deployed model losing to 50/50 on the domain subset in three of four cities
(Oslo -12.5%, Bergen -27.9%, Stavanger -15.6%, Trondheim +1.6%), so "does the
complex model earn its place" is a live question rather than a formality.

The candidates, in increasing complexity:

``Constant5050`` (complexity 0)
    The traffic-engineering null. FHWA's Traffic Monitoring Guide and TxDOT's
    design criteria both note that central urban roads sit near 50/50, so this
    is a *substantive* baseline, not a strawman — and by construction it is
    the shrinkage target of everything above it.

``ShrunkDFactor`` (complexity 1)
    A hierarchical D-factor per (hour, day-type) with empirical-Bayes partial
    pooling toward 0.5. Cells with many independent day blocks keep most of
    their observed deviation; thin cells collapse to the null. No road
    features at all, so it cannot transfer a spurious geometric pattern.

``BetaBinomialDFactor`` (complexity 2)
    The same group structure, but fit on the raw counts with a beta-binomial
    likelihood. This is the model the label actually deserves: the target is
    generated by two counts, and the day-to-day spread of a share is
    reliably wider than binomial, so an overdispersion parameter is a
    description of the data rather than a nuisance. Step 1's raw counts are
    what make it possible; on the v1 mean-share table it could not be fit.

``SimilarityWeightedLGBM`` (complexity 3)
    The currently deployed approach — gradient boosting on road/profile
    features with a Gaussian similarity kernel toward the target edges.
    Reproduced here so it competes under the same folds rather than being
    compared against numbers computed a different way.

Every model fits everything it needs — including its own shrinkage
coefficient, kernel bandwidth and dispersion — inside ``fit``. Nothing is
estimated at module import or from a full-dataset pass, because the plan
requires that no information from a test fold can reach model selection.
"""

from __future__ import annotations

import math
from dataclasses import dataclass, field
from typing import Any, Iterable, Mapping, Sequence

import numpy as np

from .dataset_schema import DirectionRow

#: Deployment clamp, matching the current `predict.py`.
SHARE_CLAMP = (0.1, 0.9)

#: Numerical floor for logit transforms.
_EPS = 1e-6


@dataclass(frozen=True)
class Prediction:
    """Central estimate plus an optional interval, aligned to input rows."""

    central: np.ndarray
    lower: np.ndarray | None = None
    upper: np.ndarray | None = None

    def __post_init__(self) -> None:
        if self.lower is not None and self.upper is not None:
            if not (len(self.central) == len(self.lower) == len(self.upper)):
                raise ValueError("prediction arrays must be the same length")

    @property
    def has_interval(self) -> bool:
        return self.lower is not None and self.upper is not None


def logit(p: np.ndarray | float) -> np.ndarray:
    arr = np.clip(np.asarray(p, dtype=float), _EPS, 1 - _EPS)
    return np.log(arr / (1 - arr))


def expit(x: np.ndarray | float) -> np.ndarray:
    return 1.0 / (1.0 + np.exp(-np.asarray(x, dtype=float)))


# ──────────────────────────────────────────────────────────────────────────
# row helpers
# ──────────────────────────────────────────────────────────────────────────
def usable(rows: Iterable[DirectionRow]) -> list[DirectionRow]:
    return [r for r in rows if r.is_usable and r.share is not None]


def orient_toward_centre(rows: Iterable[DirectionRow]) -> list[DirectionRow]:
    """Keep one heading per station — the one pointing toward the centre.

    v1 did this to remove mirrored duplicate rows (a pair contributes the
    same information twice, once as s and once as 1-s). The convention is
    kept so the tournament measures the same quantity the deployment
    predicts; `radial_cos` is the toward-centre alignment feature.
    """
    best: dict[str, tuple[float, str]] = {}
    for row in rows:
        radial = float(row.features.get("radial_cos", 0.0))
        current = best.get(row.station_id)
        if current is None or radial > current[0]:
            best[row.station_id] = (radial, row.heading)
    keep = {station: heading for station, (_r, heading) in best.items()}
    return [r for r in rows if keep.get(r.station_id) == r.heading]


def shares(rows: Sequence[DirectionRow]) -> np.ndarray:
    return np.array([float(r.share) for r in rows], dtype=float)


def group_keys(rows: Sequence[DirectionRow]) -> list[tuple[int, int]]:
    """(hour, is_weekend) — the cell the hierarchical models pool within."""
    return [(int(r.hour), int(r.is_weekend)) for r in rows]


def station_weights(rows: Sequence[DirectionRow]) -> np.ndarray:
    """Equal total influence per station.

    Hourly rows within a station are correlated, so an unweighted fit lets a
    station with many observed hours dominate. v1 applied the same
    normalisation; it is reproduced here so the tournament is like-for-like.
    """
    counts: dict[str, int] = {}
    for row in rows:
        counts[row.station_id] = counts.get(row.station_id, 0) + 1
    return np.array([1.0 / counts[r.station_id] for r in rows], dtype=float)


def n_independent_blocks(rows: Sequence[DirectionRow]) -> int:
    """Independent day blocks — the honest sample size for a spread claim."""
    return len({r.day_block_id for r in rows})


# ──────────────────────────────────────────────────────────────────────────
# base
# ──────────────────────────────────────────────────────────────────────────
class DirectionModel:
    """Interface every tournament entrant implements."""

    name: str = "base"
    complexity: int = 0
    provides_interval: bool = False

    def fit(self, rows: Sequence[DirectionRow]) -> "DirectionModel":
        raise NotImplementedError

    def predict(self, rows: Sequence[DirectionRow]) -> Prediction:
        raise NotImplementedError

    def describe(self) -> dict[str, Any]:
        return {"name": self.name, "complexity": self.complexity}


class Constant5050(DirectionModel):
    """The null: every road is an even split."""

    name = "constant_5050"
    complexity = 0

    def fit(self, rows: Sequence[DirectionRow]) -> "Constant5050":
        return self

    def predict(self, rows: Sequence[DirectionRow]) -> Prediction:
        return Prediction(central=np.full(len(rows), 0.5, dtype=float))


class ShrunkDFactor(DirectionModel):
    """Hierarchical (hour, day-type) D-factor with partial pooling to 0.5.

    Empirical Bayes: a cell's posterior mean is a precision-weighted blend of
    its own observed mean and the global 0.5, so the shrinkage weight
    ``n / (n + k)`` is *derived* from the observed between- and within-cell
    variance rather than tuned. Thin cells therefore collapse to the null
    automatically, which is the behaviour the D-factor literature supports
    for central urban roads.

    ``n`` counts independent DAY BLOCKS, not rows: 15 hourly rows from one
    station-day are one day's evidence, and treating them as 15 would
    understate the shrinkage exactly where the data is thinnest.
    """

    name = "shrunk_dfactor"
    complexity = 1
    provides_interval = True

    def __init__(self, quantiles: tuple[float, float] = (0.1, 0.9)) -> None:
        self.quantiles = quantiles
        self._cell_mean: dict[tuple[int, int], float] = {}
        self._cell_blocks: dict[tuple[int, int], int] = {}
        self._cell_sd: dict[tuple[int, int], float] = {}
        self._k: float = 1.0
        self._global_sd: float = 0.0

    def fit(self, rows: Sequence[DirectionRow]) -> "ShrunkDFactor":
        rows = usable(rows)
        if not rows:
            return self
        values = shares(rows)
        keys = group_keys(rows)
        blocks: dict[tuple[int, int], set[str]] = {}
        buckets: dict[tuple[int, int], list[float]] = {}
        for key, value, row in zip(keys, values, rows):
            buckets.setdefault(key, []).append(float(value))
            blocks.setdefault(key, set()).add(row.day_block_id)

        cell_means = {k: float(np.mean(v)) for k, v in buckets.items()}
        within = [float(np.var(v, ddof=1)) for v in buckets.values() if len(v) > 1]
        between = (float(np.var(list(cell_means.values()), ddof=1))
                   if len(cell_means) > 1 else 0.0)
        mean_within = float(np.mean(within)) if within else 0.0

        # k = within / between is the classic empirical-Bayes shrinkage
        # constant. Degenerate cases fall back to full shrinkage, which is
        # the conservative direction: toward the null.
        if between > 1e-12:
            self._k = max(mean_within / between, 0.0)
        else:
            self._k = float("inf")

        self._cell_mean = cell_means
        self._cell_blocks = {k: len(v) for k, v in blocks.items()}
        self._cell_sd = {
            k: (float(np.std(v, ddof=1)) if len(v) > 1 else 0.0)
            for k, v in buckets.items()
        }
        self._global_sd = float(np.std(values, ddof=1)) if len(values) > 1 else 0.0
        return self

    def _cell_estimate(self, key: tuple[int, int]) -> float:
        mean = self._cell_mean.get(key)
        if mean is None:
            return 0.5
        n = float(self._cell_blocks.get(key, 0))
        if not math.isfinite(self._k):
            return 0.5
        weight = n / (n + self._k) if (n + self._k) > 0 else 0.0
        return 0.5 + weight * (mean - 0.5)

    def predict(self, rows: Sequence[DirectionRow]) -> Prediction:
        central = np.array(
            [self._cell_estimate(key) for key in group_keys(rows)], dtype=float
        )
        central = np.clip(central, *SHARE_CLAMP)
        spread = np.array(
            [self._cell_sd.get(key, self._global_sd) or self._global_sd
             for key in group_keys(rows)],
            dtype=float,
        )
        # Normal interval at the requested quantiles around the shrunk mean.
        z_lo = _normal_quantile(self.quantiles[0])
        z_hi = _normal_quantile(self.quantiles[1])
        lower = np.clip(central + z_lo * spread, *SHARE_CLAMP)
        upper = np.clip(central + z_hi * spread, *SHARE_CLAMP)
        return Prediction(central=central, lower=lower, upper=upper)

    def describe(self) -> dict[str, Any]:
        return {
            **super().describe(),
            "shrinkage_k": (None if not math.isfinite(self._k) else round(self._k, 6)),
            "n_cells": len(self._cell_mean),
        }


def _normal_quantile(p: float) -> float:
    """Inverse standard normal CDF (Acklam's rational approximation).

    Implemented here so the model layer does not require scipy; accuracy is
    ~1e-9 over the range, far tighter than anything this data can resolve.
    """
    if not 0.0 < p < 1.0:
        raise ValueError("quantile must lie in (0, 1)")
    a = [-3.969683028665376e+01, 2.209460984245205e+02, -2.759285104469687e+02,
         1.383577518672690e+02, -3.066479806614716e+01, 2.506628277459239e+00]
    b = [-5.447609879822406e+01, 1.615858368580409e+02, -1.556989798598866e+02,
         6.680131188771972e+01, -1.328068155288572e+01]
    c = [-7.784894002430293e-03, -3.223964580411365e-01, -2.400758277161838e+00,
         -2.549732539343734e+00, 4.374664141464968e+00, 2.938163982698783e+00]
    d = [7.784695709041462e-03, 3.224671290700398e-01, 2.445134137142996e+00,
         3.754408661907416e+00]
    p_low, p_high = 0.02425, 1 - 0.02425
    if p < p_low:
        q = math.sqrt(-2 * math.log(p))
        return (((((c[0]*q+c[1])*q+c[2])*q+c[3])*q+c[4])*q+c[5]) / \
               ((((d[0]*q+d[1])*q+d[2])*q+d[3])*q+1)
    if p > p_high:
        q = math.sqrt(-2 * math.log(1 - p))
        return -(((((c[0]*q+c[1])*q+c[2])*q+c[3])*q+c[4])*q+c[5]) / \
               ((((d[0]*q+d[1])*q+d[2])*q+d[3])*q+1)
    q = p - 0.5
    r = q * q
    return (((((a[0]*r+a[1])*r+a[2])*r+a[3])*r+a[4])*r+a[5])*q / \
           (((((b[0]*r+b[1])*r+b[2])*r+b[3])*r+b[4])*r+1)


class BetaBinomialDFactor(DirectionModel):
    """(hour, day-type) D-factor fit on counts with overdispersion.

    The label is generated by two counts, so the natural likelihood is
    binomial — but the day-to-day spread of a real station's share is
    consistently wider than binomial, because traffic on a given day is not
    a sequence of independent coin flips. A beta-binomial adds exactly one
    parameter, the intra-day correlation ``rho``, to describe that.

    Estimating ``rho`` is what turns the interval from an assertion into a
    measurement: the binomial part is fixed by the counts, so any excess
    spread is attributed to real day-to-day variation. That is only possible
    because step 1 kept the raw counts; on v1's mean-share table there was
    nothing to fit it against.

    ``rho`` is estimated by moments per cell and pooled, then the same
    empirical-Bayes pooling as :class:`ShrunkDFactor` is applied to the mean.
    """

    name = "beta_binomial_dfactor"
    complexity = 2
    provides_interval = True

    def __init__(self, quantiles: tuple[float, float] = (0.1, 0.9)) -> None:
        self.quantiles = quantiles
        self._inner = ShrunkDFactor(quantiles=quantiles)
        self._rho: float = 0.0
        self._mean_total: dict[tuple[int, int], float] = {}
        self._global_total: float = 100.0

    def fit(self, rows: Sequence[DirectionRow]) -> "BetaBinomialDFactor":
        rows = usable(rows)
        self._inner.fit(rows)
        if not rows:
            return self

        buckets: dict[tuple[int, int], list[DirectionRow]] = {}
        for key, row in zip(group_keys(rows), rows):
            buckets.setdefault(key, []).append(row)

        rhos: list[float] = []
        totals: dict[tuple[int, int], float] = {}
        for key, group in buckets.items():
            n = np.array([r.total_count for r in group], dtype=float)
            totals[key] = float(np.mean(n)) if len(n) else 0.0
            if len(group) < 3:
                continue
            p = np.array([float(r.share) for r in group], dtype=float)
            p_bar = float(np.mean(p))
            observed = float(np.var(p, ddof=1))
            n_bar = float(np.mean(n))
            if n_bar <= 1 or not 0 < p_bar < 1:
                continue
            binomial = p_bar * (1 - p_bar) / n_bar
            if binomial <= 0:
                continue
            # var_obs = binomial * (1 + rho * (n_bar - 1))  ->  solve for rho
            rho = (observed / binomial - 1.0) / (n_bar - 1.0)
            if math.isfinite(rho):
                rhos.append(max(rho, 0.0))

        self._rho = float(np.median(rhos)) if rhos else 0.0
        self._mean_total = totals
        all_totals = [r.total_count for r in rows]
        self._global_total = float(np.mean(all_totals)) if all_totals else 100.0
        return self

    def predict(self, rows: Sequence[DirectionRow]) -> Prediction:
        central = self._inner.predict(rows).central
        keys = group_keys(rows)
        sd = np.empty(len(rows), dtype=float)
        for index, (key, mean) in enumerate(zip(keys, central)):
            n = self._mean_total.get(key, self._global_total)
            n = max(float(n), 1.0)
            var = mean * (1 - mean) / n * (1.0 + self._rho * (n - 1.0))
            sd[index] = math.sqrt(max(var, 0.0))
        z_lo = _normal_quantile(self.quantiles[0])
        z_hi = _normal_quantile(self.quantiles[1])
        return Prediction(
            central=np.clip(central, *SHARE_CLAMP),
            lower=np.clip(central + z_lo * sd, *SHARE_CLAMP),
            upper=np.clip(central + z_hi * sd, *SHARE_CLAMP),
        )

    def describe(self) -> dict[str, Any]:
        return {
            **super().describe(),
            "rho": round(self._rho, 6),
            "inner": self._inner.describe(),
        }


class SimilarityWeightedLGBM(DirectionModel):
    """The currently deployed approach, entered into the same tournament.

    Gradient boosting on road and profile features, with an optional Gaussian
    similarity kernel toward a reference feature vector (the Gothenburg
    edges), reproducing the deployment's local weighting. Quantile objectives
    supply the interval.

    Note what is NOT done here: no shrinkage is applied inside the model. The
    deployment applies James-Stein shrinkage to the point estimate *after*
    fitting, and the tournament measures the model as it would be deployed,
    so shrinkage is applied by the evaluation harness to whichever model wins
    — fit on training folds only.
    """

    name = "similarity_weighted_lgbm"
    complexity = 3
    provides_interval = True

    def __init__(self, feature_names: Sequence[str],
                 quantiles: tuple[float, float] = (0.1, 0.9),
                 reference: Mapping[str, float] | None = None,
                 n_estimators: int = 200,
                 random_state: int = 20260813) -> None:
        self.feature_names = list(feature_names)
        self.quantiles = quantiles
        self.reference = dict(reference or {})
        self.n_estimators = n_estimators
        self.random_state = random_state
        self._models: dict[str, Any] = {}
        self._bandwidth: float | None = None

    def _matrix(self, rows: Sequence[DirectionRow]) -> np.ndarray:
        out = np.zeros((len(rows), len(self.feature_names) + 3), dtype=float)
        for index, row in enumerate(rows):
            merged = {**row.features, **row.profile}
            for col, name in enumerate(self.feature_names):
                out[index, col] = float(merged.get(name, 0.0))
            base = len(self.feature_names)
            out[index, base] = math.sin(2 * math.pi * row.hour / 24)
            out[index, base + 1] = math.cos(2 * math.pi * row.hour / 24)
            out[index, base + 2] = float(row.is_weekend)
        return out

    def _similarity(self, matrix: np.ndarray) -> np.ndarray:
        """Gaussian kernel toward the reference vector.

        The bandwidth is the MEDIAN distance within the training fold, fit
        here rather than passed in — the plan requires every fitted quantity,
        bandwidth included, to be estimated inside the fold.
        """
        if not self.reference:
            return np.ones(len(matrix), dtype=float)
        ref = np.array(
            [float(self.reference.get(name, 0.0))
             for name in self.feature_names] + [0.0, 0.0, 0.0],
            dtype=float,
        )
        centre = matrix.mean(axis=0)
        scale = matrix.std(axis=0)
        scale[scale == 0] = 1.0
        distances = np.linalg.norm((matrix - ref) / scale
                                   - (centre - ref) * 0 / scale, axis=1)
        self._bandwidth = float(np.median(distances)) or 1.0
        return np.exp(-0.5 * (distances / self._bandwidth) ** 2)

    def fit(self, rows: Sequence[DirectionRow]) -> "SimilarityWeightedLGBM":
        import lightgbm as lgb

        rows = usable(rows)
        if len(rows) < 20:
            self._models = {}
            return self
        matrix = self._matrix(rows)
        target = shares(rows)
        weights = station_weights(rows) * self._similarity(matrix)

        common = dict(n_estimators=self.n_estimators, learning_rate=0.05,
                      num_leaves=15, min_child_samples=20, subsample=0.8,
                      colsample_bytree=0.8, random_state=self.random_state,
                      verbose=-1)
        self._models = {
            "q50": lgb.LGBMRegressor(objective="quantile", alpha=0.5, **common),
            "q_lo": lgb.LGBMRegressor(objective="quantile",
                                      alpha=self.quantiles[0], **common),
            "q_hi": lgb.LGBMRegressor(objective="quantile",
                                      alpha=self.quantiles[1], **common),
        }
        for model in self._models.values():
            model.fit(matrix, target, sample_weight=weights)
        return self

    def predict(self, rows: Sequence[DirectionRow]) -> Prediction:
        if not self._models:
            return Prediction(central=np.full(len(rows), 0.5, dtype=float))
        matrix = self._matrix(rows)
        central = np.clip(self._models["q50"].predict(matrix), *SHARE_CLAMP)
        lo = np.clip(self._models["q_lo"].predict(matrix), *SHARE_CLAMP)
        hi = np.clip(self._models["q_hi"].predict(matrix), *SHARE_CLAMP)
        # Monotone rearrangement (Chernozhukov et al.) — quantile crossing is
        # an estimation artifact, not information.
        lower = np.minimum(lo, hi)
        upper = np.maximum(lo, hi)
        return Prediction(central=np.clip(central, lower, upper),
                          lower=lower, upper=upper)

    def describe(self) -> dict[str, Any]:
        return {
            **super().describe(),
            "n_estimators": self.n_estimators,
            "bandwidth": self._bandwidth,
            "fitted": bool(self._models),
        }


def default_candidates(feature_names: Sequence[str],
                       reference: Mapping[str, float] | None = None,
                       quantiles: tuple[float, float] = (0.1, 0.9)
                       ) -> list[DirectionModel]:
    """The four pre-registered entrants, in increasing complexity."""
    return [
        Constant5050(),
        ShrunkDFactor(quantiles=quantiles),
        BetaBinomialDFactor(quantiles=quantiles),
        SimilarityWeightedLGBM(feature_names, quantiles=quantiles,
                               reference=reference),
    ]


__all__ = [
    "SHARE_CLAMP", "Prediction", "DirectionModel", "Constant5050",
    "ShrunkDFactor", "BetaBinomialDFactor", "SimilarityWeightedLGBM",
    "default_candidates", "usable", "orient_toward_centre", "shares",
    "station_weights", "n_independent_blocks", "logit", "expit",
]
