"""Versioned immutable metadata for the generated SUMO network.

The XML network remains the source-of-truth oracle. This index is only an
acceleration layer for repeated closure geometry, free-flow, and adjacency
queries; callers reject it when the net hash does not match and fall back to
the XML parser. It is generated by ``build_sumo_net.py`` and is rebuildable.
"""
from __future__ import annotations

import hashlib
import json
import os
import tempfile
import xml.etree.ElementTree as ET
from pathlib import Path

SCHEMA_VERSION = 1


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for block in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def _shape_midpoint(shape: str | None) -> tuple[float, float] | None:
    if not shape:
        return None
    points = []
    for raw in shape.split():
        try:
            x, y = raw.split(",", 1)
            points.append((float(x), float(y)))
        except (ValueError, TypeError):
            return None
    if not points:
        return None
    return (sum(x for x, _ in points) / len(points),
            sum(y for _, y in points) / len(points))


def build_metadata(net_path: Path) -> dict:
    root = ET.parse(net_path).getroot()
    edges: dict[str, dict] = {}
    for edge in root.findall("edge"):
        edge_id = edge.get("id")
        # plain.edg.xml (the legacy geometry oracle) contains drivable edges;
        # net.net.xml additionally contains SUMO's synthetic internal
        # junction lanes. Never attach a closure rerouter to those internals
        # or expose them as free-flow route edges.
        if not edge_id or edge.get("function") == "internal" or edge_id.startswith(":"):
            continue
        lane = edge.find("lane")
        shape = edge.get("shape") or (lane.get("shape") if lane is not None else None)
        midpoint = _shape_midpoint(shape)
        if midpoint is None:
            continue
        length = edge.get("length") or (lane.get("length") if lane is not None else None)
        speed = edge.get("speed") or (lane.get("speed") if lane is not None else None)
        try:
            length_m = float(length or 0)
            speed_m_s = float(speed or 0)
        except ValueError:
            length_m = speed_m_s = 0.0
        edges[edge_id] = {
            "midpoint": [round(midpoint[0], 3), round(midpoint[1], 3)],
            "length_m": length_m,
            "speed_m_s": speed_m_s,
        }

    successors: dict[str, list[str]] = {}
    for connection in root.findall("connection"):
        source, target = connection.get("from"), connection.get("to")
        if source and target:
            successors.setdefault(source, []).append(target)
    for source in successors:
        successors[source] = sorted(set(successors[source]))
    return {
        "schema_version": SCHEMA_VERSION,
        "net_sha256": sha256_file(net_path),
        "edges": edges,
        "successors": successors,
    }


def write_metadata(net_path: Path, output_path: Path) -> dict:
    payload = build_metadata(Path(net_path))
    output_path.parent.mkdir(parents=True, exist_ok=True)
    fd, temporary = tempfile.mkstemp(dir=output_path.parent,
                                     prefix=f".{output_path.name}.", suffix=".tmp")
    try:
        with os.fdopen(fd, "w") as stream:
            json.dump(payload, stream, separators=(",", ":"), sort_keys=True)
        os.replace(temporary, output_path)
    except BaseException:
        try:
            os.unlink(temporary)
        except FileNotFoundError:
            pass
        raise
    return payload


def load_metadata(net_path: Path, metadata_path: Path) -> dict | None:
    """Return a validated index, or ``None`` to select the XML oracle path."""
    try:
        with metadata_path.open() as stream:
            payload = json.load(stream)
        if payload.get("schema_version") != SCHEMA_VERSION:
            return None
        if payload.get("net_sha256") != sha256_file(net_path):
            return None
        if not isinstance(payload.get("edges"), dict) or \
           not isinstance(payload.get("successors"), dict):
            return None
        return payload
    except (OSError, ValueError, TypeError):
        return None
